### ISSUE TITLE
client.page.votes and client.page.revisions  isn't working properly

### ISSUE THREAD

**Issue by azureact** [ukwhatn/wikidot.py#12]
Seems there is a glitch in client.page._votes

**Comment by ukwhatn** [comment]
@azureact 

Thanks for your report!
Could you tell me more about the issue?

**Comment by azureact** [comment]
Turns out there was an issue with the target wikidot page, a user downvotes twice on the same page. Sorry to interrupt.

**Comment by ukwhatn** [comment]
@azureact 

I see!
Can you please share that page with me for reference? It would be worthwhile to be able to parse such a page.

**Comment by azureact** [comment]
@ukwhatn 
I have already asked that user to revote, but I will inform you next time I encounter it.
